### ISSUE TITLE
where can i find the "./curation/in/232geo_rm.txt" file?

### ISSUE THREAD

**Issue by liamxg** [yaotli/h5nx-emergence#2]
Dear @yaotli

**Comment by yaotli** [comment]
- KX247933_environment_Changsha_213_2014_|China|_H5N1_2014.285
- KX247918_environment_Changsha_15_2014_|China|_H5N1_2014.104
- KX247936_environment_Changsha_155_2014_|China|_H5N1_2014.252
- KX247924_environment_Changsha_115_2014_|China|_H5N1_2014.189
- KX247927_environment_Changsha_116_2014_|China|_H5N1_2014.189
- KX247915_environment_Changsha_14_2014_|China|_H5N1_2014.104
- KX247921_environment_Changsha_42_2014_|China|_H5N1_2014.110
- EPI219757_Environment_Guangxi_14313_2013_|China|_H5N1_2013.923
- EPI219772_Environment_Hunan_15252_2014_|China|_H5N1_2014.112
- EPI201002_Black_necked_Grebe_Inner_Mongolia_Brain2_2015_H5N1_|China|_H5N1_2015.359
- EPI201003_Black_necked_Grebe_Inner_Mongolia_Lung2_2015_H5N1_|China|_H5N1_2015.359
- EPI201004_Black_necked_Grebe_Inner_Mongolia_Lung3_2015_H5N1_|China|_H5N1_2015.359
- EPI201005_Black_necked_Grebe_Inner_Mongolia_Liver3_2015_H5N1_|China|_H5N1_2015.359
- EPI201006_Black_necked_Grebe_Inner_Mongolia_Brain3_2015_H5N1_|China|_H5N1_2015.359
- EPI201007_Black_necked_Grebe_Inner_Mongolia_Lung3_2_2015_H5N1_|China|_H5N1_2015.359
- EPI201008_Black_necked_Grebe_Inner_Mongolia_Oropharynx_swab3_2015_H5N1_|China|_H5N1_2015.359
- EPI201009_Black_necked_Grebe_Inner_Mongolia_Trachea3_2015_H5N1_|China|_H5N1_2015.359
- EPI201001_Black_necked_Grebe_Inner_Mongolia_Brain1_2015_H5N1_|China|_H5N1_2015.359
- CY146644_duck_Hunan_S4030_2011_|China|_H5N1_2011.855
- JX576788_environment_Hunan_3_2011_|China|_H5N1_2011.178
- MF116311_duck_China_E53_2012_|China|_H5N1_2012.380
- EPI76081_Hubei_1_2010_|China|_H5N1_2010.414
- MF116310_goose_China_E43_2012_|China|_H5N1_2012.380

**Comment by liamxg** [comment]
Thanks.
